name: Workflow de Saludo

on:
  push:
    branches: [ main ]

jobs:
  saludar-al-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Saludo al usuario
        run: echo "¡Hola, ${{ github.actor }}! Gracias por hacer push."

      - name: Listar contenido del repositorio
        run: ls -la
